import './globals.css'
import '@lvc/ui/styles.css'
import type { Metadata } from 'next'
import Header from '../components/layout/header'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="pt-16">{children}</div>
      </body>
    </html>
  )
}
